language: python
python:
    - "2.7"
    - "3.6"
    - "3.7-dev"
before_script: pip install coveralls
script:
    - "py.test"
    - "coverage run --source=photoshop_python_api setup.py test"
after_success:
    - coveralls